name: Node.js CI

on:
  push:
    branches: [master]

  jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.3]

      steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

        - name: Build
          run: |
            yarn 
            yarn build
            yarn export

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GP_PK }}
            BRANCH: gh-pages
            FOLDER: out
            CLEAN: true
